# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated from the _async directory.

"""
Resource Cleanup Example

This example demonstrates:
1. Proper resource cleanup
2. Using context managers
3. Handling cleanup on errors
4. Best practices for resource management
"""

import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))))

from agentbay import AgentBay
from agentbay import CreateSessionParams


def main():
    """Demonstrate resource cleanup."""
    print("=== Resource Cleanup Example ===\n")

    client = AgentBay()
    session = None

    try:
        print("1. Creating session...")
        session_result = client.create(CreateSessionParams(image_id="linux_latest"))
        session = session_result.session
        print(f"Session created: {session.session_id}")

        print("\n2. Performing operations...")
        session.command.execute_command("echo 'Operation 1'")
        session.command.execute_command("echo 'Operation 2'")
        print("Operations completed")

        print("\n3. Cleaning up resources...")

    except Exception as e:
        print(f"\nError occurred: {str(e)}")

    finally:
        if session:
            print("Deleting session...")
            client.delete(session)
            print("Session deleted successfully")

        print("\n=== Example completed ===")


if __name__ == "__main__":
    main()

