# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated from the _async directory.

import json

from agentbay import AgentBay, CreateSessionParams


def main() -> None:
    agent_bay = AgentBay()
    result = agent_bay.create(CreateSessionParams(image_id="linux_latest"))
    if not result.success:
        raise RuntimeError(result.error_message)

    session = result.session
    try:
        metrics_result = session.get_metrics()
        if not metrics_result.success:
            raise RuntimeError(metrics_result.error_message)

        print(json.dumps(metrics_result.raw, ensure_ascii=False, indent=2))
    finally:
        session.delete()


if __name__ == "__main__":
    main()


