name: "Multi-Language Examples Inspection"

triggers:
  # Manual trigger is implied, remove explicit manual config if it's invalid
  schedule:
    - cron: "0 2 * * *"  # Run daily at 2:00 AM

params:
  python_enabled:
    name: Enable Python Examples
    type: boolean
    default: true
  typescript_enabled:
    name: Enable TypeScript Examples
    type: boolean
    default: true
  golang_enabled:
    name: Enable Golang Examples
    type: boolean
    default: true

jobs:
  python-example-check:
    name: "Python Examples Inspection"
    when: "${{params.python_enabled}}"
    runs-on:
      - "4-16Gi"
    image: alios-8u
    timeout: 2h
    continue-on-error: true  # Continue pipeline even if this job fails
    retry:
      max: 1
      when:
        - runner_system_failure
    steps:
      - uses: checkout
      
      - uses: setup-env
        inputs:
          python-version: '3.10'
          
      - id: run-python-check
        name: "Run Python Examples Inspection"
        run: |
          echo "🔧 Setting up Python Environment..."
          python -m pip install --upgrade pip
          
          echo "📦 Installing Dependencies..."
          # Install SDK in editable mode
          python -m pip install -e ./python/
          
          # Install test & project dependencies
          python -m pip install pytest playwright python-dotenv
          
          # Install AI dependencies for analysis
          python -m pip install langchain-openai langgraph langchain-core
          
          # Install playwright browsers
          playwright install chromium || echo "⚠️ Playwright install failed"
          
          # Install extra requirements if they exist
          if [ -f "python/requirements.txt" ]; then
            python -m pip install -r python/requirements.txt
          fi
          
          echo "📋 Verifying Installed Packages..."
          python -m pip list | grep -E "agentbay|dotenv|langchain" || true
          
          echo "🚀 Starting Python Examples Inspection..."
          export AGENTBAY_API_KEY="${{secrets.AGENTBAY_API_KEY}}"
          export DASHSCOPE_API_KEY="${{secrets.DASHSCOPE_API_KEY}}"
          python scripts/check_examples.py --lang python

  typescript-example-check:
    name: "TypeScript Examples Inspection"
    when: "${{params.typescript_enabled}}"
    runs-on:
      - "4-16Gi"
    image: alios-8u
    timeout: 2h
    continue-on-error: true  # Continue pipeline even if this job fails
    retry:
      max: 1
      when:
        - runner_system_failure
    steps:
      - uses: checkout
      
      - uses: setup-env
        inputs:
          node-version: '18'
          npm-version: '10'
          
      - id: run-typescript-check
        name: "Run TypeScript Examples Inspection"
        run: |
          echo "🔧 Setting up TypeScript Environment..."
          cd typescript
          npm ci
          npm run build
          
          # Link the package
          npm link
          npm link wuying-agentbay-sdk
          
          # Install dependencies
          npm install --no-save ts-node
          npx playwright install chromium || echo "⚠️ Playwright install failed"
          
          # Install Python AI dependencies for analysis runner
          echo "📦 Installing Python AI Dependencies..."
          python -m pip install langchain-openai langgraph langchain-core
          
          cd ..
          echo "🚀 Starting TypeScript Examples Inspection..."
          export AGENTBAY_API_KEY="${{secrets.AGENTBAY_API_KEY}}"
          export DASHSCOPE_API_KEY="${{secrets.DASHSCOPE_API_KEY}}"
          python scripts/check_examples.py --lang typescript

  golang-example-check:
    name: "Golang Examples Inspection"
    when: "${{params.golang_enabled}}"
    runs-on:
      - "4-16Gi"
    image: alios-8u
    timeout: 2h
    continue-on-error: true  # Continue pipeline even if this job fails
    retry:
      max: 1
      when:
        - runner_system_failure
    steps:
      - uses: checkout
      
      - uses: setup-env
        inputs:
          go-version: '1.24.3'
          
      - id: run-golang-check
        name: "Run Golang Examples Inspection"
        run: |
          echo "🔧 Setting up Golang Environment..."
          cd golang
          go env -w GOPROXY=https://goproxy.cn,direct
          go mod download
          
          # Install playwright
          go run github.com/playwright-community/playwright-go/cmd/playwright@latest install chromium || echo "⚠️ Playwright install failed"
          
          cd ..
          # Install Python AI dependencies for analysis runner
          echo "📦 Installing Python AI Dependencies..."
          python -m pip install langchain-openai langgraph langchain-core
          
          echo "🚀 Starting Golang Examples Inspection..."
          export AGENTBAY_API_KEY="${{secrets.AGENTBAY_API_KEY}}"
          export DASHSCOPE_API_KEY="${{secrets.DASHSCOPE_API_KEY}}"
          python scripts/check_examples.py --lang golang

  summary:
    name: "Examples Inspection Summary"
    needs: ["python-example-check", "typescript-example-check", "golang-example-check"]
    # Ensure summary runs even if previous jobs failed
    if: always()
    runs-on:
      - "4-16Gi"
    steps:
      - run: |
          echo "=========================================="
          echo "      Examples Inspection Completed"
          echo "=========================================="
          echo ""
          
          # Check status of each job
          PYTHON_STATUS="${{jobs.python-example-check.status}}"
          TS_STATUS="${{jobs.typescript-example-check.status}}"
          GO_STATUS="${{jobs.golang-example-check.status}}"
          
          echo "Python Check: $PYTHON_STATUS"
          echo "TypeScript Check: $TS_STATUS"
          echo "Golang Check: $GO_STATUS"
          
          # Fail the summary job if any critical check failed
          if [ "$PYTHON_STATUS" != "success" ] || [ "$TS_STATUS" != "success" ] || [ "$GO_STATUS" != "success" ]; then
            echo "❌ One or more example checks failed."
            exit 1
          fi
          
          echo "✅ All checks passed successfully."
