name: "Multi-Language Examples Inspection"

triggers:
  # Manual trigger is implied, remove explicit manual config if it's invalid
  # schedule:
  #   - cron: "0 2 * * *"  # Run daily at 2:00 AM

params:
  python_enabled:
    name: Enable Python Examples
    type: boolean
    default: true
  typescript_enabled:
    name: Enable TypeScript Examples
    type: boolean
    default: true
  golang_enabled:
    name: Enable Golang Examples
    type: boolean
    default: true

jobs:
  example-check:
    name: "Examples Inspection"
    runs-on:
      - "4-16Gi"
    image: alios-8u
    timeout: 5h
    retry:
      max: 1
      when:
        - runner_system_failure
    steps:
      - uses: checkout
      
      - uses: setup-env
        inputs:
          python-version: '3.10'
          node-version: '18'
          npm-version: '10'
          go-version: '1.24.3'
          
      - id: run-checks
        name: "Run Example Checks"
        run: |
          echo "🔧 Setting up Environment..."
          
          # Install Python Dependencies
          echo "🐍 Setting up Python..."
          python -m pip install --upgrade pip
          python -m pip install -e ./python/
          python -m pip install pytest playwright python-dotenv langchain-openai langgraph langchain-core
          playwright install chromium || echo "⚠️ Playwright install failed"
          if [ -f "python/requirements.txt" ]; then
            python -m pip install -r python/requirements.txt
          fi
          
          # Install TypeScript Dependencies
          echo "📜 Setting up TypeScript..."
          if [ "${{params.typescript_enabled}}" == "true" ]; then
            cd typescript
            npm ci
            npm run build
            npm link
            npm link wuying-agentbay-sdk
            npm install --no-save ts-node
            npx playwright install chromium || echo "⚠️ Playwright install failed"
            cd ..
          fi
          
          # Install Golang Dependencies
          echo "🐹 Setting up Golang..."
          if [ "${{params.golang_enabled}}" == "true" ]; then
            cd golang
            go env -w GOPROXY=https://goproxy.cn,direct
            go mod download
            go run github.com/playwright-community/playwright-go/cmd/playwright@latest install chromium || echo "⚠️ Playwright install failed"
            cd ..
          fi
          
          echo "🚀 Starting Examples Inspection..."
          export AGENTBAY_API_KEY="${{secrets.AGENTBAY_API_KEY}}"
          export DASHSCOPE_API_KEY="${{secrets.DASHSCOPE_API_KEY}}"
          
          # Run checks sequentially but capture failures
          FAILED=false
          
          if [ "${{params.python_enabled}}" == "true" ]; then
            echo "=== Running Python Checks ==="
            set +e
            python scripts/check_examples.py --lang python
            if [ $? -ne 0 ]; then FAILED=true; fi
            set -e
          fi
          
          if [ "${{params.typescript_enabled}}" == "true" ]; then
            echo "=== Running TypeScript Checks ==="
            set +e
            python scripts/check_examples.py --lang typescript
            if [ $? -ne 0 ]; then FAILED=true; fi
            set -e
          fi
          
          if [ "${{params.golang_enabled}}" == "true" ]; then
            echo "=== Running Golang Checks ==="
            set +e
            python scripts/check_examples.py --lang golang
            if [ $? -ne 0 ]; then FAILED=true; fi
            set -e
          fi
          
          # Display report if exists
          if [ -f "example_check_report.md" ]; then
            echo ""
            echo "=========================================="
            echo "      Examples Inspection Report"
            echo "=========================================="
            echo ""
            cat example_check_report.md
            
            # Also append to CI summary
            cat example_check_report.md >> $AONE_CI_SUMMARY_MD
          fi
          
          if [ "$FAILED" = "true" ]; then
            echo "❌ One or more example checks failed."
            exit 1
          else
            echo "✅ All enabled checks passed successfully."
            exit 0
          fi
