# agentbay SDK Multi-Language CI/CD Pipeline
name: "agentbay SDK Multi-Language Quality Assurance"

triggers:
  merge_request:
    types:
      - opened
      - reopened
    target-branches:
      - "**"

# Strategy configuration to prevent jobs from being accidentally cancelled
strategy:
  cancel-in-progress: false
  fail-fast: false

params:
  python_enabled:
    name: Enable Python Testing
    type: boolean
    default: true
  typescript_enabled:
    name: Enable TypeScript Testing
    type: boolean
    default: true
  golang_enabled:
    name: Enable Golang Testing
    type: boolean
    default: true
  runs_on_resources:
    name: Resource Specification
    description: "Runtime container resource specification"
    default: "4-16Gi"
    options:
      - "4-16Gi"
      - "8-32Gi"
      - "16-64Gi"

jobs:
  # Python testing job
  python-lint-test:
    name: "Python Code Quality Check"
    when: "${{params.python_enabled}}"
    runs-on:
      - "${{params.runs_on_resources}}"
    image: alios-8u
    timeout: 1h
    retry:
      max: 2
      when:
        - runner_system_failure
        - stuck_or_timeout_failure
    steps:

      - uses: checkout
      - uses: setup-env
        inputs:
          python-version: '3.10'
      
      - id: python-lint
        continue-on-error: true
        name: "Python Code Format Check & Security Check"
        when: "${{params.python_enabled}}"
        run: |
          cd python
          python -m pip config set global.timeout 300
          python -m pip config set global.retries 3
          python -m pip install --upgrade pip
          # Install tools for linting
          pip install black isort flake8 mypy bandit pip-audit
          pip install types-requests types-aiohttp types-Pillow types-setuptools types-pydantic || true
          # Run all checks
          black agentbay tests --check --diff
          echo "Format check completed"
          isort --check-only --diff --verbose agentbay tests
          echo "Quality check completed"
          flake8 agentbay tests --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=agentbay/modules/browser/eval
          echo "Flake8 check completed"
          mypy agentbay --install-types --no-error-summary --install-types --non-interactive
          echo "Type check completed"
          python -m bandit -r agentbay/ -v --skip B105,B106,B107
          echo "Bandit scan completed"
          echo "Executing pip-audit dependency vulnerability scan..."
          pip-audit --desc
          echo "Dependency vulnerability scan completed"
      
      - id: python-test
        continue-on-error: false
        when: "${{params.python_enabled}}"
        name: "Python Unit Tests"
        run: |
          cd python
          python -m pip config set global.timeout 600
          python -m pip config set global.retries 5
          python -m pip install --upgrade pip
          # Install all dependencies directly (avoid poetry timeout issues)
          pip install "darabonba-core>=1.0.0,<2.0.0" \
                      "alibabacloud-tea-openapi>=0.4.0rc3" \
                      "cryptography>=44.0.0" \
                      "httpx>=0.28.1" \
                      "alibabacloud-tea-util>=0.3.13" \
                      "python-dotenv>=1.0.0" \
                      "pydantic>=2.0" \
                      "playwright>=1.5.0" \
                      "loguru>=0.7.0"
          # Install test dependencies
          pip install pytest pytest-cov pytest-asyncio
          # Add current directory to PYTHONPATH so tests can import agentbay
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          # Run tests
          pytest tests/unit -v


  # TypeScript testing job
  typescript-lint-test:
    name: "TypeScript Code Quality Check & Security Check"
    when: "${{params.typescript_enabled}}"
    image: alios-8u
    runs-on:
      - "${{params.runs_on_resources}}"
    retry:
      max: 2
      when:
        - runner_system_failure
        - stuck_or_timeout_failure
    steps:
      - uses: checkout
      - uses: setup-env
        inputs:
          node-version: "18"
          npm-version: "10"
          npm-cache: true
        
      - id: typescript-lint
        continue-on-error: true
        name: "TypeScript Code Format Check"
        when: "${{params.typescript_enabled}}"
        run: |
          cd typescript
          # Set npm timeout and retry strategy
          npm config set fetch-timeout 300000
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          npm ci --prefer-offline --no-audit
          npm run lint
      - id: typescript-test-unit
        continue-on-error: false
        when: "${{params.typescript_enabled}}"
        name: "TypeScript Unit Tests"
        run: |
          cd typescript
          # Reuse installed dependencies to avoid duplicate installation
          npm run build
          npm run test:unit

  # Golang testing job
  golang-lint-test:
    name: "Golang Code Quality Check & Security Check"
    when: "${{params.golang_enabled}}"
    image: alios-8u
    runs-on:
      - "${{params.runs_on_resources}}"
    retry:
      max: 2
      when:
        - runner_system_failure
        - stuck_or_timeout_failure
    steps:
      
      - uses: checkout
      - uses: setup-env
        inputs:
          go-version: "1.24.3"
          go-mod-cache: true
          go-cache: true
      
      - id: golang-lint
        continue-on-error: true
        name: "Golang Code Format Check"
        when: "${{params.golang_enabled}}"
        run: |
          # Configure Go environment
          go env -w GOPROXY=https://goproxy.cn,direct
          go env -w GOSUMDB=sum.golang.org
          go env -w GONOSUMDB=""
          cd golang
          # Download dependencies (use go-mod-cache from setup-env)
          go mod download
          go mod verify
          # Run basic checks that don't require additional tools
          echo "Building code..."
          go build -v ./api/client/... || echo "Build completed with warnings"
          echo "Running go vet..."
          go vet ./... || echo "Vet completed with warnings"
          # Run go fmt check (non-destructive)
          echo "Checking code formatting..."
          UNFORMATTED=$(gofmt -l . | grep -v "api/client" || true)
          if [ -n "$UNFORMATTED" ]; then
            echo "The following files need formatting:"
            echo "$UNFORMATTED"
          else
            echo "All files are properly formatted"
          fi
      
      - id: golang-unit-test
        continue-on-error: false
        when: "${{params.golang_enabled}}"
        name: "Golang Unit Tests"
        run: |
          # Configure Go environment
          go env -w GOPROXY=https://goproxy.cn,direct
          go env -w GOSUMDB=sum.golang.org
          go env -w GONOSUMDB=""
          cd golang
          # Dependencies already downloaded in lint step, just verify
          go mod verify
          # Run tests with race detector
          go test -race -v ./tests/pkg/unit/...

  summary:
    name: "Multi-Language Quality Check Summary"
    needs: ["python-lint-test", "typescript-lint-test", "golang-lint-test"]
    runs-on:
      - "4-16Gi"
    steps:
      - run: |
          echo "=========================================="
          echo "    agentbay SDK Multi-Language Quality Check Summary"
          echo "=========================================="
          echo ""
          echo "All prerequisite jobs have completed successfully!"
          echo ""
          echo "✅ Python Lint & Unit Tests: PASSED"
          echo "✅ TypeScript Lint & Unit Tests: PASSED"
          echo "✅ Golang Lint & Unit Tests: PASSED"
          echo ""
          echo "=========================================="
          echo "✅ All Quality Checks: PASSED"
          echo "=========================================="