name: "Smart Integration Test"

params:
  test_type:
    name: Test Type
    type: string
    default: "all"
    options:
      - "all"
      - "python"
      - "typescript"
      - "golang"

jobs:
  smart-integration-test:
    name: "Smart Integration Test"
    runs-on:
      - "4-16Gi"
    image: alios-8u
    timeout: 3h
    retry:
      max: 2
      when:
        - runner_system_failure
        - stuck_or_timeout_failure
    steps:
      - uses: checkout
      
      - uses: setup-env
        inputs:
          python-version: '3.12'
          
      - id: run-smart-tests
        name: "Run Smart Tests"
        run: |
          echo "🔄 Installing dependencies for Smart Test Runner..."
          
          # Install Go if needed for golang or all test types
          if [ "${{params.test_type}}" = "golang" ] || [ "${{params.test_type}}" = "all" ]; then
            echo "🐹 Installing Go environment..."
            # Check if Go is already available
            if ! command -v go &> /dev/null; then
              # Download and install Go 1.21 to local directory
              mkdir -p $HOME/go-install
              cd $HOME/go-install
              if [ ! -f go1.21.0.linux-amd64.tar.gz ]; then
                echo "📥 Downloading Go from mirror..."
                # Try multiple mirrors for better connectivity in China
                wget -O go1.21.0.linux-amd64.tar.gz https://golang.google.cn/dl/go1.21.0.linux-amd64.tar.gz || \
                wget -O go1.21.0.linux-amd64.tar.gz https://mirrors.aliyun.com/golang/go1.21.0.linux-amd64.tar.gz || \
                wget -O go1.21.0.linux-amd64.tar.gz https://go.dev/dl/go1.21.0.linux-amd64.tar.gz
              fi
              if [ -f go1.21.0.linux-amd64.tar.gz ]; then
                echo "📦 Extracting Go..."
                tar -xzf go1.21.0.linux-amd64.tar.gz
                export PATH=$HOME/go-install/go/bin:$PATH
                export GOROOT=$HOME/go-install/go
                echo "✅ Go installed to local directory"
              else
                echo "❌ Failed to download Go"
              fi
              cd $(pwd)
            fi
            go version || echo "❌ Go installation failed"
            
            # Setup Golang dependencies
            if command -v go &> /dev/null && [ -d "golang" ]; then
              echo "📦 Setting up Golang dependencies..."
              # Set Go proxy to use faster mirror in China
              export GOPROXY=https://goproxy.cn,direct
              export GOSUMDB=sum.golang.google.cn
              cd golang && go mod download && cd .. || echo "⚠️ Go mod download failed"
            fi
          fi
          
          # Install Node.js if needed for typescript or all test types
          if [ "${{params.test_type}}" = "typescript" ] || [ "${{params.test_type}}" = "all" ]; then
            echo "📜 Installing Node.js environment..."
            # Check if Node.js is already available
            if ! command -v node &> /dev/null; then
              # Install Node.js using NodeSource binary distribution (no sudo required)
              mkdir -p $HOME/nodejs
              cd $HOME/nodejs
              if [ ! -f node-v18.18.0-linux-x64.tar.xz ]; then
                echo "📥 Downloading Node.js from mirror..."
                # Try multiple mirrors for better connectivity in China
                wget -O node-v18.18.0-linux-x64.tar.xz https://npmmirror.com/mirrors/node/v18.18.0/node-v18.18.0-linux-x64.tar.xz || \
                wget -O node-v18.18.0-linux-x64.tar.xz https://mirrors.aliyun.com/nodejs-release/v18.18.0/node-v18.18.0-linux-x64.tar.xz || \
                wget -O node-v18.18.0-linux-x64.tar.xz https://nodejs.org/dist/v18.18.0/node-v18.18.0-linux-x64.tar.xz
              fi
              if [ -f node-v18.18.0-linux-x64.tar.xz ]; then
                echo "📦 Extracting Node.js..."
                tar -xf node-v18.18.0-linux-x64.tar.xz
                export PATH=$HOME/nodejs/node-v18.18.0-linux-x64/bin:$PATH
                echo "✅ Node.js installed to local directory"
              else
                echo "❌ Failed to download Node.js"
              fi
              cd $(pwd)
            fi
            node --version || echo "❌ Node.js installation failed"
            npm --version || echo "❌ npm installation failed"
            
            # Setup TypeScript dependencies
            if command -v npm &> /dev/null && [ -d "typescript" ]; then
              echo "📦 Setting up TypeScript dependencies..."
              # Set npm registry to use faster mirror in China
              npm config set registry https://registry.npmmirror.com
              cd typescript && npm install && cd .. || echo "⚠️ npm install failed"
            fi
          fi
          
          # Setup Python environment (always needed for the test runner itself)
          python -m pip config set global.timeout 600
          python -m pip config set global.retries 5
          python -m pip install --upgrade pip
          
          # Install Python dependencies similar to unit test job
          pip install "darabonba-core>=1.0.0,<2.0.0" \
                      "alibabacloud-tea-openapi>=0.4.0rc3" \
                      "cryptography>=44.0.0" \
                      "httpx>=0.28.1" \
                      "alibabacloud-tea-util>=0.3.13" \
                      "python-dotenv>=1.0.0" \
                      "pydantic>=2.0" \
                      "playwright>=1.5.0" \
                      "loguru>=0.7.0"
          
          # Install test dependencies
          pip install pytest pytest-cov pytest-asyncio
          
          # Install AI dependencies
          pip install langchain-openai langgraph langchain-core
          
          echo "🔧 Setting up environment..."
          # Ensure we're in the correct working directory
          cd /aoneci/runner/work/source || exit 1
          echo "📂 Current working directory: $(pwd)"
          
          # Install SDK in editable mode with correct path
          if [ -d "python" ]; then
            pip install -e ./python/
            echo "✅ Python SDK installed successfully"
          else
            echo "❌ Python directory not found"
            ls -la
            exit 1
          fi
          
          # Set PYTHONPATH similar to unit test job
          export PYTHONPATH="${PYTHONPATH}:$(pwd)/python"
          export AGENTBAY_API_KEY="${{secrets.AGENTBAY_API_KEY}}"
          export DASHSCOPE_API_KEY="${{secrets.DASHSCOPE_API_KEY}}"
          
          echo "🚀 Starting Smart Test Runner..."
          echo "Working directory: $(pwd)"
          echo "Python path: $PYTHONPATH"
          
          # Set up PATH for installed tools
          if [ "${{params.test_type}}" = "golang" ] || [ "${{params.test_type}}" = "all" ]; then
            export PATH=$HOME/go-install/go/bin:$PATH
            export GOROOT=$HOME/go-install/go
            echo "🔍 Checking Go installation..."
            which go || echo "❌ Go not found in PATH"
            go version || echo "❌ Go version check failed"
          fi
          
          if [ "${{params.test_type}}" = "typescript" ] || [ "${{params.test_type}}" = "all" ]; then
            export PATH=$HOME/nodejs/node-v18.18.0-linux-x64/bin:$PATH
            echo "🔍 Checking Node.js installation..."
            which node || echo "❌ Node not found in PATH"
            node --version || echo "❌ Node version check failed"
            which npm || echo "❌ npm not found in PATH"
            npm --version || echo "❌ npm version check failed"
          fi
          
          # Run the smart test runner and capture exit code with updated PATH
          # Ensure we have the correct working directory
          cd /aoneci/runner/work/source || exit 1
          
          # Set up comprehensive PATH with all installed tools
          export PATH="$HOME/go-install/go/bin:$HOME/nodejs/node-v18.18.0-linux-x64/bin:$PATH"
          
          if python scripts/smart_test_runner.py --test-type="${{params.test_type}}"; then
            echo "✅ Smart Test Runner completed successfully"
            
            # Check if test report was generated
          if [ -f "test_report.md" ]; then
            echo "✅ Test report generated successfully"
            
            # Display in CI Summary (Markdown format)
            echo "## 🤖 Smart Integration Test Report" >> $AONE_CI_SUMMARY_MD
            echo "" >> $AONE_CI_SUMMARY_MD
            cat test_report.md >> $AONE_CI_SUMMARY_MD
            
            # Also show in console for immediate viewing
            echo "📋 Test report preview:"
            head -50 test_report.md
            
            # Archive as build artifact
            mkdir -p artifacts
            cp test_report.md artifacts/smart_test_report.md
          else
            echo "⚠️ No test report generated"
            echo "## ❌ Smart Integration Test Report" >> $AONE_CI_SUMMARY_MD
            echo "No test report was generated. Check the logs above for errors." >> $AONE_CI_SUMMARY_MD
          fi
          else
            echo "❌ Smart Test Runner failed with exit code $?"
            echo "❌ CI pipeline will now fail"
            exit 1
          fi

