name: "Smart Integration Test"

params:
  test_type:
    name: Test Type
    type: string
    default: "all"
    options:
      - "all"
      - "python"
      - "typescript"
      - "golang"

jobs:
  smart-integration-test:
    name: "Smart Integration Test"
    runs-on:
      - "4-16Gi"
    image: alios-8u
    timeout: 1h
    retry:
      max: 2
      when:
        - runner_system_failure
        - stuck_or_timeout_failure
    steps:
      - uses: checkout
      
      - uses: setup-env
        inputs:
          python-version: '3.12'
          
      - id: install-dependencies
        name: "Install Dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest langchain-openai langgraph langchain-core alibabacloud_tea_openapi alibabacloud_credentials alibabacloud_tea_util alibabacloud_endpoint_util
          # Install the SDK itself in editable mode
          python -m pip install -e python/
          
      - id: run-smart-tests
        name: "Run Smart Tests"
        run: |
          echo "Starting Smart Test Runner..."
          export PYTHONPATH="${PYTHONPATH}:$(pwd)/python"
          export AGENTBAY_API_KEY="${{secrets.AGENTBAY_API_KEY}}"
          export DASHSCOPE_API_KEY="${{secrets.DASHSCOPE_API_KEY}}"
          python scripts/smart_test_runner.py --test-type="${{params.test_type}}"
          
          # Check if test report was generated
          if [ -f "test_report.md" ]; then
            echo "✅ Test report generated successfully"
            echo "📋 Test report content:"
            cat test_report.md
          else
            echo "⚠️ No test report generated"
          fi

