import time
# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated from the _async directory.

"""
示例：使用PageUse Agent的AgentBay接口访问阿里云并搜索“AgentBay帮助文档”
打开 https://www.aliyun.com
搜索“AgentBay帮助文档”，点击第一条搜索结果并进入“帮助文档”，滚动到页面底部
重点：全程使用 BrowserAgent API
"""

import os
from agentbay import AgentBay
from agentbay import CreateSessionParams
from agentbay import BrowserOption
from agentbay import ActOptions as ActOptions


def main():
    # Get API key from environment variable
    api_key = os.getenv("AGENTBAY_API_KEY")
    if not api_key:
        print("Error: AGENTBAY_API_KEY environment variable not set")
        return

    # Initialize AgentBay client
    print("Initializing AgentBay client...")
    agent_bay = AgentBay(api_key=api_key)

    # Create a session
    print("Creating a new session...")
    params = CreateSessionParams(
        image_id="browser_latest",  # Specify the image ID
    )
    session_result = agent_bay.create(params)

    if session_result.success:
        session = session_result.session
        print(f"Session created with ID: {session.session_id}")

        if session.browser.initialize(BrowserOption()):
            print("Browser initialized successfully")
            agent = session.browser.agent

            agent.navigate("https://www.aliyun.com")

            agent.act(
                ActOptions(action="搜索框输入'AgentBay帮助文档'并回车")
            )
            agent.act(ActOptions(action="点击搜索结果中的第一项"))
            agent.act(ActOptions(action="点击'帮助文档'"))
            agent.act(ActOptions(action="滚动页面到底部"))

            time.sleep(5)
        else:
            print("Failed to initialize browser")
        agent_bay.delete(session)


if __name__ == "__main__":
    main()
