# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

from __future__ import annotations

from typing import Any, Callable, Optional

from ..._common.exceptions import AgentBayError


class WsConnectionState(str):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    RECONNECTING = "RECONNECTING"
    ERROR = "ERROR"


class WsClient:
    def __init__(self, ws_url: str, http_token: str, **kwargs: Any):
        self._ws_url = ws_url
        self._http_token = http_token

    def connect(self) -> None:
        raise AgentBayError(
            "WS long connection is only supported in the async Python SDK for now"
        )

    def close(self) -> None:
        return

    def call_stream(
        self,
        *,
        target: str,
        data: dict[str, Any],
        on_event: Optional[Callable[[str, dict[str, Any]], None]],
        on_end: Optional[Callable[[str, dict[str, Any]], None]],
        on_error: Optional[Callable[[str, Exception], None]],
    ):
        raise AgentBayError(
            "WS long connection is only supported in the async Python SDK for now"
        )
