import time
# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

import os
from typing import TYPE_CHECKING, Any, Dict, List, Optional

from ..api.models import ListSkillMetaDataRequest, GetSkillMetaDataRequest
from .._common.models.skill_info import SkillInfo, SkillsMetadataResult

if TYPE_CHECKING:
    from .agentbay import AgentBay


DEFAULT_OFFICIAL_SKILLS_ROOT = "/home/wuying/skills"


class SyncBetaSkillsService:
    """
    Beta skills service.

    Capabilities:
    - Get skills metadata via POP Action `GetSkillMetaData` (supports filtering).
    - List official skills metadata via POP Action `ListSkillMetaData` (deprecated).
    """

    def __init__(self, agent_bay: "AgentBay", skills_root: Optional[str] = None):
        self._agent_bay = agent_bay
        root = (
            skills_root
            or os.environ.get("AGENTBAY_OFFICIAL_SKILLS_ROOT", "").strip()
            or DEFAULT_OFFICIAL_SKILLS_ROOT
        )
        self._skills_root = root.rstrip("/") or DEFAULT_OFFICIAL_SKILLS_ROOT

    def _build_skill_dir(self, name: str) -> str:
        n = (name or "").strip().lstrip("/")
        return f"{self._skills_root}/{n}" if n else self._skills_root

    def get_metadata(
        self,
        image_id: Optional[str] = None,
        skill_names: Optional[List[str]] = None,
    ) -> SkillsMetadataResult:
        """Get skills metadata without starting a sandbox.

        Args:
            image_id: Image ID to determine the skills root path. Uses default image if not specified.
            skill_names: Filter by skill names. Returns all visible skills if not specified.

        Returns:
            SkillsMetadataResult with skills list and skills_root_path.

        Raises:
            RuntimeError: If the API call fails.
        """
        request = GetSkillMetaDataRequest(
            authorization=f"Bearer {self._agent_bay.api_key}",
            image_id=image_id,
            skill_group_ids=skill_names,
        )

        max_attempts = 3
        delay_s = 0.2
        last_err: Optional[BaseException] = None
        resp = None
        for attempt in range(1, max_attempts + 1):
            try:
                resp = self._agent_bay.client.get_skill_meta_data(request)
                last_err = None
                break
            except Exception as e:
                last_err = e
                msg = str(e)
                if attempt < max_attempts and (
                    "ServiceUnavailable" in msg
                    or "statusCode': 503" in msg
                    or "code: 503" in msg
                ):
                    time.sleep(delay_s)
                    delay_s *= 2
                    continue
                raise

        if last_err is not None:
            raise RuntimeError(f"GetSkillMetaData failed: {last_err}") from last_err

        body = getattr(resp, "body", None)
        if body is None:
            raise RuntimeError("GetSkillMetaData failed: missing response body")

        if getattr(body, "success", None) is None or not body.success:
            code = str(getattr(body, "code", "") or "")
            msg = str(getattr(body, "message", "") or "")
            if code:
                raise RuntimeError(f"GetSkillMetaData failed: [{code}] {msg}")
            raise RuntimeError(f"GetSkillMetaData failed: {msg or 'Unknown error'}")

        data = getattr(body, "data", None)
        if data is None:
            raise RuntimeError("GetSkillMetaData failed: missing Data field")

        skill_path = str(getattr(data, "skill_path", "") or "")
        meta_data_list = getattr(data, "meta_data_list", None) or []

        skills: List[SkillInfo] = []
        for raw in meta_data_list:
            name = str(getattr(raw, "name", "") or "").strip()
            if not name:
                continue
            description = str(getattr(raw, "description", "") or "")
            skills.append(SkillInfo(name=name, description=description))

        return SkillsMetadataResult(
            skills=skills,
            skills_root_path=skill_path,
        )

    def list_metadata(self) -> List[Dict[str, str]]:
        """List official skills metadata.

        .. deprecated::
            Use :meth:`get_metadata` instead.

        Returns:
            List[Dict[str, str]]: Each item contains name and description.
        """
        request = ListSkillMetaDataRequest(
            authorization=f"Bearer {self._agent_bay.api_key}",
        )

        max_attempts = 3
        delay_s = 0.2
        last_err: Optional[BaseException] = None
        resp: Any = None
        for attempt in range(1, max_attempts + 1):
            try:
                resp = self._agent_bay.client.list_skill_meta_data(request)
                last_err = None
                break
            except Exception as e:
                last_err = e
                msg = str(e)
                if attempt < max_attempts and (
                    "ServiceUnavailable" in msg or "statusCode': 503" in msg or "code: 503" in msg
                ):
                    time.sleep(delay_s)
                    delay_s *= 2
                    continue
                raise

        if last_err is not None:
            raise RuntimeError(f"ListSkillMetaData failed: {last_err}") from last_err

        body = getattr(resp, "body", None)
        if body is None:
            raise RuntimeError("ListSkillMetaData failed: missing response body")

        if getattr(body, "success", None) is None or not body.success:
            code = str(getattr(body, "code", "") or "")
            msg = str(getattr(body, "message", "") or "")
            if code:
                raise RuntimeError(f"ListSkillMetaData failed: [{code}] {msg}")
            raise RuntimeError(f"ListSkillMetaData failed: {msg or 'Unknown error'}")

        data = getattr(body, "data", None) or []
        if not isinstance(data, list):
            raise RuntimeError("ListSkillMetaData failed: invalid Data field")

        items: List[Dict[str, str]] = []
        for raw in data:
            name = str(getattr(raw, "name", "") or "").strip()
            if not name:
                continue
            description = str(getattr(raw, "description", "") or "")
            items.append(
                {
                    "name": name,
                    "description": description,
                }
            )
        return items


class SyncBetaNamespace:
    """Beta namespace container for experimental features."""

    def __init__(self, agent_bay: "AgentBay"):
        self.skills = SyncBetaSkillsService(agent_bay)

