# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

from typing import TYPE_CHECKING, Callable, Optional

from .._common.config import _BROWSER_DATA_PATH
from .._common.exceptions import BrowserError
from .._common.logger import _log_api_response_with_details, get_logger
from .._common.models import BrowserNotifyMessage, BrowserCallback
from ..api.models import InitBrowserRequest
from .base_service import BaseService
from .browser_operator import BrowserOperator

# Initialize logger for this module
_logger = get_logger("browser")

if TYPE_CHECKING:
    from .._common.models import BrowserOption
    from .session import Session

class Browser(BaseService):
    """
    Browser provides browser-related operations for the session.
    """

    def __init__(self, session: "Session"):
        self.session = session
        self._endpoint_url = None
        self._initialized = False
        self._option = None

        # New: operator is the recommended way
        self.operator = BrowserOperator(self.session, self)

        # Deprecated: agent is kept for backward compatibility
        self._agent = self.operator
        self._agent_deprecation_warned = False

        self.endpoint_router_port = None

        # Internal callback management
        self._user_callback: Optional[BrowserCallback] = None
        self._ws_callback_registered = False

    @property
    def agent(self):
        """
        **Deprecated**: Use `operator` instead. This property will be removed in a future version.

        Example:
            ```python
            # Old way (deprecated):
            # session.browser.operator.navigate(url)

            # New way (recommended):
            session.browser.operator.navigate(url)
            ```
        """
        if not self._agent_deprecation_warned:
            _logger.warning(
                f"[ ⚠️ DeprecationWarning] browser.agent is deprecated and will be removed in a future version. "
                "Please use browser.operator instead.",
            )
            self._agent_deprecation_warned = True
        return self._agent

    def initialize(self, option: Optional["BrowserOption"] = None) -> bool:
        """
        Initialize the browser instance with the given options synchronously.
        Returns True if successful, False otherwise.

        Args:
            option (BrowserOption, optional): Browser configuration options. If None, default options are used.

        Returns:
            bool: True if initialization was successful, False otherwise.

        Example:
            ```python
            create_result = agent_bay.create()
            session = create_result.session
            # Use default options
            session.browser.initialize()
            # Or with specific options
            browser_option = BrowserOption(use_stealth=True)
            session.browser.initialize(browser_option)
            session.delete()
            ```
        """
        if self.is_initialized():
            return True

        if option is None:
            option = BrowserOption()

        try:
            browser_option_dict = option._to_map()

            # Set enableRecord based on session.enableBrowserReplay (only when explicitly set)
            if hasattr(self.session, "enableBrowserReplay") and self.session.enableBrowserReplay is not None:
                browser_option_dict["enableRecord"] = self.session.enableBrowserReplay

            request = InitBrowserRequest(
                authorization=f"Bearer {self.session._get_api_key()}",
                session_id=self.session._get_session_id(),
                persistent_path=_BROWSER_DATA_PATH,
                browser_option=browser_option_dict,
            )
            # Use async client method
            response = self.session._get_client().init_browser(request)
            _logger.debug(f"Response from init_browser: {response}")
            response_map = response.to_map()
            body = response_map.get("body", {})
            data = body.get("Data", {})
            success = data.get("Port") is not None
            if success:
                self.endpoint_router_port = data.get("Port")
                self._initialized = True
                self._option = option
                _log_api_response_with_details(
                    api_name="InitBrowser (async)",
                    success=True,
                    key_fields={
                        "port": data.get("Port"),
                        "status": "successfully initialized",
                    },
                )
                _logger.info("Browser instance successfully initialized")
            return success
        except Exception as e:
            _logger.exception(
                f"❌ Failed to initialize browser instance synchronously"
            )
            self._initialized = False
            self._endpoint_url = None
            self._option = None
            return False

    def init(self, option: Optional["BrowserOption"] = None) -> bool:
        """
        Alias for initialize.
        """
        return self.initialize(option)

    def destroy(self):
        """
        Destroy the browser instance manually.
        """
        self._stop_browser()

    def screenshot(self, page, full_page: bool = False, **options) -> bytes:
        """
        Takes a screenshot of the specified page with enhanced options and error handling.

        Args:
            page (Page): The Playwright Page object to take a screenshot of. This is a required parameter.
            full_page (bool): Whether to capture the full scrollable page. Defaults to False.
            **options: Additional screenshot options that will override defaults.
                      Common options include:
                      - type (str): Image type, either 'png' or 'jpeg' (default: 'png')
                      - quality (int): Quality of the image, between 0-100 (jpeg only)
                      - timeout (int): Maximum time in milliseconds (default: 60000)
                      - animations (str): How to handle animations (default: 'disabled')
                      - caret (str): How to handle the caret (default: 'hide')
                      - scale (str): Scale setting (default: 'css')

        Returns:
            bytes: Screenshot data as bytes.

        Raises:
            BrowserError: If browser is not initialized.
            RuntimeError: If screenshot capture fails.
        """
        # Check if browser is initialized
        if not self.is_initialized():
            raise BrowserError("Browser must be initialized before calling screenshot.")
        if page is None:
            raise ValueError("Page cannot be None")
        # Set default enhanced options
        enhanced_options = {
            "animations": "disabled",
            "caret": "hide",
            "scale": "css",
            "timeout": options.get("timeout", 60000),
            "full_page": full_page,  # Use the function parameter, not options
            "type": options.get("type", "png"),
        }

        # Update with user-provided options (but full_page is already set from function parameter)
        enhanced_options.update(options)

        try:
            # Wait for page to load
            # page.wait_for_load_state("networkidle")
            page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
            page.wait_for_load_state("domcontentloaded", timeout=30000)
            # Scroll to load all content (especially for lazy-loaded elements)
            self._scroll_to_load_all_content(page)

            # Ensure images with data-src attributes are loaded
            page.evaluate(
                """
                () => {
                    document.querySelectorAll('img[data-src]').forEach(img => {
                        if (!img.src && img.dataset.src) {
                            img.src = img.dataset.src;
                        }
                    });
                    // Also handle background-image[data-bg]
                    document.querySelectorAll('[data-bg]').forEach(el => {
                        if (!el.style.backgroundImage) {
                            el.style.backgroundImage = `url(${el.dataset.bg})`;
                        }
                    });
                }
            """
            )

            # Wait a bit for images to load
            page.wait_for_timeout(1500)
            final_height = page.evaluate("document.body.scrollHeight")
            page.set_viewport_size(
                {"width": 1920, "height": min(final_height, 10000)}
            )

            # Take the screenshot
            screenshot_bytes = page.screenshot(**enhanced_options)
            _logger.info("Screenshot captured successfully.")
            return screenshot_bytes

        except Exception as e:
            # Convert exception to string safely to avoid comparison issues
            try:
                error_str = str(e)
            except:
                error_str = "Unknown error occurred"
            error_msg = f"Failed to capture screenshot: {error_str}"
            _logger.error(error_msg)
            raise RuntimeError(error_msg) from e

    def _scroll_to_load_all_content(
        self, page, max_scrolls: int = 8, delay_ms: int = 1200
    ):
        """Sync version of _scroll_to_load_all_content."""
        last_height = 0
        for _ in range(max_scrolls):
            page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
            page.wait_for_timeout(delay_ms)
            new_height = page.evaluate(
                "Math.max(document.body.scrollHeight, document.documentElement.scrollHeight)"
            )
            if new_height == last_height:
                break
            last_height = new_height

    def _stop_browser(self):
        """
        Stop the browser instance, internal use only.
        """
        if self.is_initialized():
            self.session.call_mcp_tool(
                "stopChrome",
                {},
            )
            self._initialized = False
            self._endpoint_router_port = None
            self._endpoint_url = None
            self._option = None
        else:
            raise BrowserError("Browser is not initialized. Cannot stop browser.")

    def _internal_ws_callback(self, payload: dict) -> None:
        _logger.debug(f"Browser layer received notification: {payload}")

        # Basic validation: data field should exist and not be None
        if payload.get("data") is None:
            _logger.debug(f"Ignoring notification with empty data: {payload}")
            return

        # Dispatch to user callback if set
        if self._user_callback:
            try:
                notify_msg = BrowserNotifyMessage._from_map(payload.get("data"))
                self._user_callback(notify_msg)
            except Exception as e:
                _logger.error(f"Error when calling user callback: {e}")

    def register_callback(
        self, 
        callback: BrowserCallback
    ) -> bool:
        """
        Register a callback function to handle browser-related push notifications from sandbox.

        Args:
            callback (Callable[[BrowserNotifyMessage], None]): Callback function that receives 
                a BrowserNotifyMessage object containing notification details such as type, code,
                message, action, and extra_params.

        Returns:
            bool: True if the callback was successfully registered.

        Example:
            ```python
            def on_browser_callback(notify_msg: BrowserNotifyMessage):
                print(f"Type: {notify_msg.type}")
                print(f"Code: {notify_msg.code}")
                print(f"Message: {notify_msg.message}")
                print(f"Action: {notify_msg.action}")
                print(f"Extra params: {notify_msg.extra_params}")

            create_result = agent_bay.create()
            session = create_result.session

            # Initialize browser
            session.browser.initialize()

            # Register callback
            success = session.browser.register_callback(on_browser_callback)

            # ... do work ...

            # Unregister when done
            session.browser.unregister_callback()
            session.delete()
            ```
        """
        try:
            # Set user callback (replaces any existing callback)
            self._user_callback = callback
            _logger.info("Set user callback")

            # Register internal callback to ws_client only once
            if not self._ws_callback_registered:
                ws_client = self.session._get_ws_client()
                ws_client.connect()
                ws_client.register_callback("wuying_cdp_mcp_server", self._internal_ws_callback)
                self._ws_callback_registered = True
                _logger.debug("Registered internal ws_callback to ws_client")

            return True
        except Exception as e:
            _logger.error(f"Failed to register user callback: {e}")
            return False


    def unregister_callback(self) -> None:
        """
        Unregister the previously registered callback function.

        Example:
            ```python
            def on_browser_callback(notify_msg: BrowserNotifyMessage):
                print(f"Notification - Type: {notify_msg.type}, Message: {notify_msg.message}")

            create_result = agent_bay.create()
            session = create_result.session

            session.browser.initialize()

            session.browser.register_callback(on_browser_callback)

            # ... do work ...

            # Unregister callback
            session.browser.unregister_callback()

            session.delete()
            ```
        """
        try:
            # Clear user callback
            self._user_callback = None
            _logger.info("Cleared user callback")

            # Unregister from ws_client
            if self._ws_callback_registered:
                ws_client = self.session._get_ws_client()
                ws_client.unregister_callback("wuying_cdp_mcp_server", self._internal_ws_callback)
                ws_client.close()
                self._ws_callback_registered = False
                _logger.debug("Unregistered internal ws_callback from ws_client")
        except Exception as e:
            _logger.error(f"Failed to unregister user callback: {e}")


    def send_notify_message(
        self,
        notify_message: BrowserNotifyMessage
    ) -> bool:
        """
        Send a BrowserNotifyMessage to sandbox.

        Args:
            notify_message (BrowserNotifyMessage): The notify message to send.

        Returns:
            bool: True if the notify message was successfully sent, False otherwise.

        Example:
            ```python
            def on_browser_callback(notify_msg: BrowserNotifyMessage):
                print(f"Type: {notify_msg.type}")
                print(f"Code: {notify_msg.code}")
                print(f"Message: {notify_msg.message}")
                print(f"Action: {notify_msg.action}")
                print(f"Extra params: {notify_msg.extra_params}")

            create_result = agent_bay.create()
            session = create_result.session

            # Initialize browser
            session.browser.initialize()

            # Register callback
            success = session.browser.register_callback(on_browser_callback)

            # ... do work ...

            # Send notify message
            notify_message = BrowserNotifyMessage(
                type="call-for-user",
                id=3,
                code=199,
                message="user handle done",
                action="takeoverdone",
                extra_params={}
            )
            session.browser.send_notify_message(notify_message)

            # Unregister when done
            session.browser.unregister_callback()
            session.delete()
            ```
        """
        try:
            ws_client = self.session._get_ws_client()

            # Send notify message through ws_client
            ws_client.send_message(
                target="wuying_cdp_mcp_server",
                data=notify_message._to_map()
            )
            _logger.info(f"Successfully sent browser notify message, notify_message: {notify_message._to_map()}")
            return True
        except Exception as e:
            _logger.error(f"Failed to send notify message: {e}")
            return False


    def send_takeover_done(
        self,
        notify_id: int
    ) -> bool:
        """
        Send a takeoverdone notify message to sandbox.

        Args:
            notify_id (int): The notification ID associated with the takeover request message.

        Returns:
            bool: True if the takeoverdone notify message was successfully sent, False otherwise.

        Example:
            ```python
            def on_browser_callback(notify_msg: BrowserNotifyMessage):
                # receive call-for-user "takeover" action
                if notify_msg.action == "takeover":
                    takeover_notify_id = notify_msg.id

                    ## ... do work in other thread...
                    # send takeoverdone notify message
                    session.browser.send_takeover_done(takeover_notify_id)
                    ## ... end...

            create_result = agent_bay.create()
            session = create_result.session

            # Initialize browser
            session.browser.initialize()

            # Register callback
            success = session.browser.register_callback(on_browser_callback)

            # ... do work ...

            # Unregister when done
            session.browser.unregister_callback()
            session.delete()
            ```
        """
        try:
            # Get ws_client
            ws_client = self.session._get_ws_client()

            # Build takeoverdone notify message
            notify_message = BrowserNotifyMessage(
                type="call-for-user",
                id=notify_id,
                code=199,
                message="user handle done",
                action="takeoverdone",
                extra_params={}
            )
            message_data = notify_message._to_map()

            # Send message through ws_client
            ws_client.send_message(
                target="wuying_cdp_mcp_server",
                data=message_data
            )

            _logger.info(f"Successfully sent browser takeoverdone notify message, notify_id: {notify_id}")
            return True

        except Exception as e:
            _logger.error(f"Failed to send browser notify message: {e}")
            return False


    def get_endpoint_url(self) -> str:
        """
        Returns the endpoint URL if the browser is initialized, otherwise raises an exception.
        When initialized, always fetches the latest CDP url from session.get_link().

        Returns:
            str: The browser CDP endpoint URL.

        Raises:
            BrowserError: If browser is not initialized or endpoint URL cannot be retrieved.

        Example:
            ```python
            create_result = agent_bay.create()
            session = create_result.session
            browser_option = BrowserOption()
            session.browser.initialize(browser_option)
            endpoint_url = session.browser.get_endpoint_url()
            print(f"CDP Endpoint: {endpoint_url}")
            session.delete()
            ```
        """
        if not self.is_initialized():
            raise BrowserError(
                "Browser is not initialized. Cannot access endpoint URL."
            )
        try:
            from ..api.models import GetCdpLinkRequest

            request = GetCdpLinkRequest(
                authorization=f"Bearer {self.session.agent_bay.api_key}",
                session_id=self.session.session_id,
            )
            # Sync call
            response = self.session.agent_bay.client.get_cdp_link(
                request
            )
            if response.body and response.body.success and response.body.data:
                self._endpoint_url = response.body.data.url
            else:
                error_msg = response.body.message if response.body else "Unknown error"
                raise BrowserError(f"Failed to get CDP link: {error_msg}")
            return self._endpoint_url
        except Exception as e:
            raise BrowserError(f"Failed to get endpoint URL from session: {e}")

    def get_option(self) -> Optional["BrowserOption"]:
        """
        Returns the current BrowserOption used to initialize the browser, or None if not set.

        Returns:
            Optional[BrowserOption]: The browser options if initialized, None otherwise.

        Example:
            ```python
            create_result = agent_bay.create()
            session = create_result.session
            browser_option = BrowserOption(use_stealth=True)
            session.browser.initialize(browser_option)
            current_options = session.browser.get_option()
            print(f"Stealth mode: {current_options.use_stealth}")
            session.delete()
            ```
        """
        return self._option

    def is_initialized(self) -> bool:
        """
        Returns True if the browser was initialized, False otherwise.

        Returns:
            bool: True if browser is initialized, False otherwise.

        Example:
            ```python
            create_result = agent_bay.create()
            session = create_result.session
            print(f"Initialized: {session.browser.is_initialized()}")
            browser_option = BrowserOption()
            session.browser.initialize(browser_option)
            print(f"Initialized: {session.browser.is_initialized()}")
            session.delete()
            ```
        """
        return self._initialized
