# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

import json
from typing import Any, Dict, Optional

from .._common.exceptions import AgentBayError, CommandError
from .._common.logger import get_logger
from .._common.models.command import CommandResult
from .._common.models.response import ApiResponse
from .base_service import BaseService

# Initialize _logger for this module
_logger = get_logger("command")


class Command(BaseService):
    """
    Handles command execution operations in the AgentBay cloud environment.
    """

    def execute_command(
        self,
        command: str,
        timeout_ms: int = 60000,
        cwd: Optional[str] = None,
        envs: Optional[Dict[str, str]] = None,
    ) -> CommandResult:
        """
        Execute a shell command with a timeout.

        Args:
            command: The shell command to execute.
            timeout_ms: The timeout for the command execution in milliseconds. Default is 60000ms (60s).
            cwd: The working directory for command execution. Optional.
            envs: Environment variables as a dictionary. Optional.

        Returns:
            CommandResult: Result object containing success status, execution
                output, exit code, stdout, stderr, and error message if any.

        Raises:
            CommandError: If the command execution fails.

        Example:
            ```python
            result = await session.command.execute_command("ls -la")
            print(result.output)
            print(result.stdout)
            print(result.exit_code)
            ```
        """
        try:
            # Build request arguments
            args = {"command": command, "timeout_ms": timeout_ms}
            if cwd is not None:
                args["cwd"] = cwd
            if envs is not None:
                args["envs"] = envs

            result = self.session.call_mcp_tool("shell", args)
            _logger.debug(f"Execute command response: {result}")

            if result.success:
                # Try to parse the new JSON format response
                try:
                    # Parse JSON string from result.data
                    if isinstance(result.data, str):
                        data_json = json.loads(result.data)
                    else:
                        data_json = result.data

                    # Extract fields from new format
                    stdout = data_json.get("stdout", "")
                    stderr = data_json.get("stderr", "")
                    error_code = data_json.get("errorCode", 0)
                    trace_id = data_json.get("traceId", "")

                    # Determine success based on errorCode (0 means success)
                    success = error_code == 0

                    # For backward compatibility, output should be stdout if available, otherwise stderr
                    output = stdout if stdout else stderr

                    return CommandResult(
                        request_id=result.request_id,
                        success=success,
                        output=output,
                        exit_code=error_code,
                        stdout=stdout,
                        stderr=stderr,
                    )
                except (json.JSONDecodeError, TypeError, AttributeError) as e:
                    # Fallback to old format if JSON parsing fails
                    _logger.debug(f"Failed to parse JSON response, using old format: {e}")
                    return CommandResult(
                        request_id=result.request_id,
                        success=True,
                        output=result.data if isinstance(result.data, str) else str(result.data),
                    )
            else:
                return CommandResult(
                    request_id=result.request_id,
                    success=False,
                    error_message=result.error_message or "Failed to execute command",
                )
        except Exception as e:
            return CommandResult(
                request_id="",
                success=False,
                error_message=f"Failed to execute command: {e}",
            )
