"""Utility functions and templates."""

from .command_templates import (
    APP_BLACKLIST_TEMPLATE,
    APP_WHITELIST_TEMPLATE,
    HIDE_NAVIGATION_BAR_TEMPLATE,
    MOBILE_COMMAND_TEMPLATES,
    RESOLUTION_LOCK_TEMPLATE,
    SHOW_NAVIGATION_BAR_TEMPLATE,
    UNINSTALL_BLACKLIST_TEMPLATE,
)
from .key_normalizer import normalize_keys

__all__ = [
    "normalize_dict",
    "MOBILE_COMMAND_TEMPLATES",
    "RESOLUTION_LOCK_TEMPLATE",
    "APP_WHITELIST_TEMPLATE",
    "APP_BLACKLIST_TEMPLATE",
    "HIDE_NAVIGATION_BAR_TEMPLATE",
    "SHOW_NAVIGATION_BAR_TEMPLATE",
    "UNINSTALL_BLACKLIST_TEMPLATE",
]
