import os
import shutil
import sys
import re
from pathlib import Path

# Add the project root to path to import unasync rules if needed
# But for examples, we might need custom rules since it's consuming the SDK, not defining it.

def generate_sync_examples(src_dir: Path, dest_dir: Path):
    """
    Generate sync examples from async examples.
    """
    if dest_dir.exists():
        shutil.rmtree(dest_dir)
    dest_dir.mkdir(parents=True, exist_ok=True)

    print(f"Generating sync examples from {src_dir} to {dest_dir}...")

    for src_file in src_dir.rglob("*.py"):
        # Skip __init__.py or other utility files if necessary
        # if src_file.name.startswith("__"):
        #     continue
            
        rel_path = src_file.relative_to(src_dir)
        dest_file = dest_dir / rel_path
        
        dest_file.parent.mkdir(parents=True, exist_ok=True)
        
        convert_file(src_file, dest_file)

    # Copy non-python files (README.md, images, etc.)
    for src_file in src_dir.rglob("*"):
        if src_file.is_dir() or src_file.suffix == ".py" or src_file.name == "__pycache__":
            continue
        
        rel_path = src_file.relative_to(src_dir)
        dest_file = dest_dir / rel_path
        dest_file.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_file, dest_file)

def convert_file(src_path: Path, dest_path: Path):
    with open(src_path, "r", encoding="utf-8") as f:
        code = f.read()

    # 1. Replace Imports
    # from agentbay import AsyncAgentBay -> from agentbay import AgentBay
    code = code.replace("AsyncAgentBay", "AgentBay")
    code = code.replace("AsyncSession", "Session")
    # Remove specific async imports if they become redundant or rename them
    code = code.replace("from agentbay.async_api import", "from agentbay import")
    
    # 2. Handle asyncio.sleep BEFORE removing asyncio import
    # asyncio.sleep(x) -> time.sleep(x)
    if "asyncio.sleep" in code:
        code = code.replace("asyncio.sleep", "time.sleep")
        # Add time import if not present
        if "import time" not in code:
            # Find where to insert time import (after other imports)
            lines = code.split('\n')
            insert_index = 0
            for i, line in enumerate(lines):
                if line.startswith('import ') or line.startswith('from '):
                    insert_index = i + 1
            if insert_index > 0:
                lines.insert(insert_index, 'import time')
                code = '\n'.join(lines)
    
    # 3. Remove asyncio import
    code = re.sub(r"^import asyncio\n", "", code, flags=re.MULTILINE)
    code = re.sub(r"^import asyncio\r\n", "", code, flags=re.MULTILINE)

    # 4. Remove async/await keywords
    code = re.sub(r"async def ", "def ", code)
    code = re.sub(r"async with ", "with ", code)
    code = re.sub(r"await ", "", code)
    
    # 5. Handle asyncio.run()
    # asyncio.run(main()) -> main()
    code = re.sub(r"asyncio\.run\((.*?)\)", r"\1", code)
    
    # 6. Handle specific renames/replacements
    # e.g. async_playwright -> sync_playwright (if used in examples)
    code = code.replace("async_playwright", "sync_playwright")
    
    # Replace method names with _async suffix
    code = code.replace(".initialize_async(", ".initialize(")
    code = code.replace(".navigate_async(", ".navigate(")
    code = code.replace(".screenshot_async(", ".screenshot(")

    # 7. Header
    header = "# DO NOT EDIT THIS FILE MANUALLY.\n# This file is auto-generated from the _async directory.\n\n"
    
    with open(dest_path, "w", encoding="utf-8") as f:
        f.write(header + code)
    
    print(f"Generated: {dest_path}")

if __name__ == "__main__":
    root_dir = Path(__file__).parent.parent
    examples_dir = root_dir / "docs" / "examples"
    
    async_dir = examples_dir / "_async"
    sync_dir = examples_dir / "_sync"
    
    if not async_dir.exists():
        print(f"Error: Source directory {async_dir} does not exist.")
        sys.exit(1)
        
    generate_sync_examples(async_dir, sync_dir)

