# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

"""Integration tests for browser viewport."""
import os

import pytest
from playwright.sync_api import sync_playwright

from agentbay import AgentBay
from agentbay._common.params.session_params import CreateSessionParams
from agentbay._sync.browser import BrowserOption


@pytest.fixture(scope="module")
def agent_bay():
    api_key = os.environ.get("AGENTBAY_API_KEY")
    if not api_key:
        pytest.skip("AGENTBAY_API_KEY environment variable not set")
    return AgentBay(api_key=api_key)


@pytest.fixture
def browser_session(agent_bay):
    params = CreateSessionParams(image_id="browser_latest")
    result = agent_bay.create(params)
    assert result.success
    yield result.session
    result.session.delete()


@pytest.mark.sync
def test_browser_viewport_size(browser_session):
    """Test setting browser viewport size."""
    browser = browser_session.browser
    browser.initialize(BrowserOption())

    endpoint_url = browser.get_endpoint_url_async()
    p = sync_playwright().start()
    playwright_browser = p.chromium.connect_over_cdp(endpoint_url)
    page = playwright_browser.new_page()

    # Set viewport
    page.set_viewport_size({"width": 1280, "height": 720})

    # Get viewport
    viewport = page.viewport_size
    assert viewport["width"] == 1280
    assert viewport["height"] == 720
    print(f"Viewport set to: {viewport}")

    page.close()
    playwright_browser.close()
    p.stop()


@pytest.mark.sync
def test_browser_mobile_viewport(browser_session):
    """Test mobile viewport."""
    browser = browser_session.browser
    browser.initialize(BrowserOption())

    endpoint_url = browser.get_endpoint_url_async()
    p = sync_playwright().start()
    playwright_browser = p.chromium.connect_over_cdp(endpoint_url)
    page = playwright_browser.new_page()

    # Set mobile viewport
    page.set_viewport_size({"width": 375, "height": 667})

    viewport = page.viewport_size
    assert viewport["width"] == 375
    assert viewport["height"] == 667
    print(f"Mobile viewport: {viewport}")

    page.close()
    playwright_browser.close()
    p.stop()
