# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

"""Integration tests for Browser Agent functionality."""
import os
import pytest
import pytest
from playwright.sync_api import sync_playwright
from pydantic import BaseModel

from agentbay import AgentBay
from agentbay.browser import BrowserOption, BrowserFingerprint, BrowserProxy
from agentbay._async.browser_agent import ActOptions, ExtractOptions, ObserveOptions
from agentbay.session_params import CreateSessionParams


class DummySchema(BaseModel):
    """Schema for extract test."""
    title: str


def _mask_secret(secret: str, visible: int = 4) -> str:
    """Mask a secret value, keeping only the last `visible` characters."""
    if not secret:
        return ""
    if len(secret) <= visible:
        return "*" * len(secret)
    return ("*" * (len(secret) - visible)) + secret[-visible:]


def is_windows_user_agent(user_agent: str) -> bool:
    """Check if user agent indicates Windows OS."""
    if not user_agent:
        return False
    user_agent_lower = user_agent.lower()
    windows_indicators = [
        'windows nt',
        'win32',
        'win64',
        'windows',
        'wow64'
    ]
    return any(indicator in user_agent_lower for indicator in windows_indicators)


@pytest.fixture(scope="module")
def agent_bay():
    """Create AsyncAgentBay instance."""
    api_key = os.environ.get("AGENTBAY_API_KEY")
    if not api_key:
        pytest.skip("AGENTBAY_API_KEY environment variable not set")
    print(f"\napi_key = {_mask_secret(api_key)}")
    return AgentBay(api_key=api_key)


@pytest.fixture
def browser_session(agent_bay):
    """Create a session with browser_latest image."""
    print("\nCreating a new session for browser agent testing...")
    session_param = CreateSessionParams(image_id="browser_latest")
    result = agent_bay.create(session_param)
    assert result.success, f"Failed to create session: {result.error_message}"
    session = result.session
    print(f"Session created with ID: {session.session_id}")
    yield session
    print("\nCleaning up: Deleting the session...")
    session.delete()


@pytest.mark.sync
def test_initialize_browser(browser_session):
    """Test basic browser initialization."""
    browser = browser_session.browser
    assert browser is not None

    init_result = browser.initialize(BrowserOption())
    assert init_result is True

    # FIX: Use get_endpoint_url_async() instead of get_endpoint_url()
    endpoint_url = browser.get_endpoint_url_async()
    print(f"endpoint_url = {endpoint_url}")
    assert endpoint_url is not None

    time.sleep(10)

    p = sync_playwright().start()
    playwright_browser = p.chromium.connect_over_cdp(endpoint_url)
    assert playwright_browser is not None

    page = playwright_browser.new_page()
    page.goto("http://www.baidu.com")
    title = page.title()
    print(f"page.title() = {title}")

    assert title is not None
    page.close()
    playwright_browser.close()
    p.stop()


@pytest.mark.sync
def test_initialize_browser_with_fingerprint(browser_session):
    """Test browser initialization with fingerprint."""
    browser = browser_session.browser
    assert browser is not None

    option = BrowserOption(
        use_stealth=True,
        fingerprint=BrowserFingerprint(
            devices=["desktop"],
            operating_systems=["windows"],
            locales=["zh-CN"],
        )
    )
    init_result = browser.initialize(option)
    assert init_result is True

    # FIX: Use get_endpoint_url_async() instead of get_endpoint_url()
    endpoint_url = browser.get_endpoint_url_async()
    print(f"endpoint_url = {endpoint_url}")
    assert endpoint_url is not None

    time.sleep(10)

    p = sync_playwright().start()
    playwright_browser = p.chromium.connect_over_cdp(endpoint_url)
    assert playwright_browser is not None
    default_context = playwright_browser.contexts[0]
    assert default_context is not None

    page = default_context.new_page()
    page.goto("https://httpbin.org/user-agent", timeout=60000)
    response = page.evaluate("() => JSON.parse(document.body.textContent)")
    user_agent = response["user-agent"]
    print(f"user_agent = {user_agent}")
    assert user_agent is not None
    is_windows = is_windows_user_agent(user_agent)
    assert is_windows is True

    page.close()
    playwright_browser.close()
    p.stop()


@pytest.mark.sync
def test_act_success(browser_session):
    """Test browser agent act operation."""
    browser = browser_session.browser
    assert browser is not None

    init_result = browser.initialize(BrowserOption())
    assert init_result is True

    # FIX: Use get_endpoint_url_async() instead of get_endpoint_url()
    endpoint_url = browser.get_endpoint_url_async()
    print(f"endpoint_url = {endpoint_url}")
    assert endpoint_url is not None

    p = sync_playwright().start()
    playwright_browser = p.chromium.connect_over_cdp(endpoint_url)
    assert playwright_browser is not None

    page = playwright_browser.new_page()
    page.goto("http://www.baidu.com")
    title = page.title()
    assert title is not None

    result = browser.agent.act(ActOptions(action="Click search button"), page)
    print(f"result = {result}")

    assert result.success is True
    assert hasattr(result, 'action')

    page.close()
    playwright_browser.close()
    p.stop()


@pytest.mark.sync
def test_observe_success(browser_session):
    """Test browser agent observe operation."""
    browser = browser_session.browser
    assert browser is not None

    init_result = browser.initialize(BrowserOption())
    assert init_result is True

    # FIX: Use get_endpoint_url_async() instead of get_endpoint_url()
    endpoint_url = browser.get_endpoint_url_async()
    print(f"endpoint_url = {endpoint_url}")
    assert endpoint_url is not None

    p = sync_playwright().start()
    playwright_browser = p.chromium.connect_over_cdp(endpoint_url)
    assert playwright_browser is not None

    page = playwright_browser.new_page()
    page.goto("http://www.baidu.com")
    title = page.title()
    assert title is not None

    result, observe_results = browser.agent.observe(
        ObserveOptions(instruction="Find the search button"),
        page
    )
    print(f"result = {result}")
    print(f"observe_results = {observe_results}")

    assert result is True
    assert len(observe_results) > 0
    assert hasattr(observe_results[0], 'description')

    page.close()
    playwright_browser.close()
    p.stop()


@pytest.mark.sync
def test_extract_success(browser_session):
    """Test browser agent extract operation."""
    browser = browser_session.browser
    assert browser is not None

    init_result = browser.initialize(BrowserOption())
    assert init_result is True

    # FIX: Use get_endpoint_url_async() instead of get_endpoint_url()
    endpoint_url = browser.get_endpoint_url_async()
    print(f"endpoint_url = {endpoint_url}")
    assert endpoint_url is not None

    p = sync_playwright().start()
    playwright_browser = p.chromium.connect_over_cdp(endpoint_url)
    assert playwright_browser is not None

    page = playwright_browser.new_page()
    page.goto("http://www.baidu.com")
    title = page.title()
    assert title is not None

    result, obj = browser.agent.extract(
        ExtractOptions(instruction="Extract the title", schema=DummySchema),
        page
    )
    print(f"result = {result}")
    print(f"obj = {obj}")
    assert result is True
    assert obj is not None
    assert hasattr(obj, 'title')

    page.close()
    playwright_browser.close()
    p.stop()


@pytest.mark.sync
def test_restricted_proxy_ip_comparison(agent_bay):
    """Test restricted proxy by comparing IP addresses before and after proxy setup."""
    print("\n=== test restricted proxy IP comparison ===")

    # Phase 1: Initialize browser without proxy and get original IP
    print("phase 1: initialize browser without proxy...")
    session_param1 = CreateSessionParams(image_id="browser_latest")
    result1 = agent_bay.create(session_param1)
    assert result1.success
    session1 = result1.session

    browser1 = session1.browser
    no_proxy_option = BrowserOption()
    init_result1 = browser1.initialize(no_proxy_option)
    assert init_result1 is True

    # FIX: Use get_endpoint_url_async() instead of get_endpoint_url()
    endpoint_url1 = browser1.get_endpoint_url_async()
    print(f"endpoint_url = {endpoint_url1}")
    assert endpoint_url1 is not None

    time.sleep(5)

    # Get original IP
    p1 = sync_playwright().start()
    playwright_browser1 = p1.chromium.connect_over_cdp(endpoint_url1)
    assert playwright_browser1 is not None

    context1 = playwright_browser1.contexts[0]
    page1 = context1.new_page()
    page1.goto("https://httpbin.org/ip")

    try:
        response = page1.evaluate("() => JSON.parse(document.body.textContent)")
        original_ip = response.get("origin", "").strip()
        print(f"original IP: {original_ip}")
    except Exception as e:
        print(f"get original IP failed: {e}")
        original_ip = None

    page1.close()
    playwright_browser1.close()
    p1.stop()

    # Delete current session
    session1.delete()

    time.sleep(3)

    # Phase 2: Create new session with restricted proxy
    print("phase 2: create new session with restricted proxy...")
    restricted_proxy = BrowserProxy(
        proxy_type="wuying",
        strategy="restricted"
    )

    proxy_option = BrowserOption(proxies=[restricted_proxy])
    session_param2 = CreateSessionParams(image_id="browser_latest")
    result2 = agent_bay.create(session_param2)
    assert result2.success
    session2 = result2.session

    browser2 = session2.browser
    init_result2 = browser2.initialize(proxy_option)
    assert init_result2 is True

    # Verify proxy configuration
    saved_option = browser2.get_option()
    assert saved_option.proxies is not None
    assert len(saved_option.proxies) == 1
    assert saved_option.proxies[0].type == "wuying"
    assert saved_option.proxies[0].strategy == "restricted"
    print("✓ proxy config validation success")

    # FIX: Use get_endpoint_url_async() instead of get_endpoint_url()
    endpoint_url2 = browser2.get_endpoint_url_async()
    print(f"proxy mode endpoint_url = {endpoint_url2}")

    time.sleep(5)

    # Get proxy IP
    p2 = sync_playwright().start()
    playwright_browser2 = p2.chromium.connect_over_cdp(endpoint_url2)
    assert playwright_browser2 is not None

    context2 = playwright_browser2.contexts[0]
    page2 = context2.new_page()
    page2.goto("https://httpbin.org/ip")

    try:
        response2 = page2.evaluate("() => JSON.parse(document.body.textContent)")
        proxy_ip = response2.get("origin", "").strip()
        print(f"proxy IP: {proxy_ip}")
    except Exception as e:
        print(f"get proxy IP failed: {e}")
        proxy_ip = None

    page2.close()
    playwright_browser2.close()
    p2.stop()

    # Clean up session2
    session2.delete()

    # Compare IPs
    if original_ip and proxy_ip:
        if original_ip != proxy_ip:
            print(f"✅ static proxy test success! IP changed: {original_ip} -> {proxy_ip}")
        else:
            print(f"⚠️  warning: proxy IP is the same, maybe proxy not working: {original_ip}")
            pytest.fail("proxy IP is the same, maybe proxy not working")
    else:
        print("⚠️  failed to compare IP, but proxy config applied")

