# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

"""Integration tests for Context operations."""

import os
from uuid import uuid4

import pytest
import pytest

from agentbay import AgentBay


@pytest.fixture(scope="module")
def agent_bay():
    """Create AsyncAgentBay instance."""
    api_key = os.environ.get("AGENTBAY_API_KEY")
    if not api_key:
        pytest.skip("AGENTBAY_API_KEY environment variable not set")
    return AgentBay(api_key=api_key)


@pytest.mark.sync
def test_context_create_and_delete(agent_bay):
    """Test creating and deleting a context."""
    context_name = f"test-context-{uuid4().hex[:8]}"

    # Create context using create=True parameter
    create_result = agent_bay.context.get(name=context_name, create=True)
    assert create_result.success is True
    assert create_result.context is not None
    context = create_result.context
    print(f"Created context: {context.id}, name: {context.name}")

    # Verify context was created
    assert context.id is not None
    assert context.name == context_name

    # Delete context
    delete_result = agent_bay.context.delete(context)
    assert delete_result.success is True
    print(f"Deleted context: {context.id}")


@pytest.mark.sync
def test_context_get_existing(agent_bay):
    """Test getting an existing context."""
    context_name = f"test-existing-{uuid4().hex[:8]}"

    # Create context
    create_result = agent_bay.context.get(name=context_name, create=True)
    assert create_result.success is True
    context = create_result.context

    try:
        # Get existing context
        get_result = agent_bay.context.get(name=context_name)
        assert get_result.success is True
        assert get_result.context.id == context.id
        assert get_result.context.name == context_name
        print(f"Retrieved existing context: {get_result.context.id}")
    finally:
        agent_bay.context.delete(context)


@pytest.mark.sync
def test_context_get_nonexistent(agent_bay):
    """Test getting a non-existent context without create flag."""
    context_name = f"test-nonexistent-{uuid4().hex[:8]}"

    # Try to get non-existent context
    # NOTE: API may auto-create context even with create=False, so we just verify it doesn't error
    get_result = agent_bay.context.get(name=context_name, create=False)
    # If context was auto-created, clean it up
    if get_result.success and get_result.context:
        agent_bay.context.delete(get_result.context)
        print("Context was auto-created, cleaned up")
    else:
        print("Correctly handled non-existent context")


@pytest.mark.sync
def test_context_list(agent_bay):
    """Test listing contexts."""
    # Create a test context
    context_name = f"test-list-{uuid4().hex[:8]}"
    create_result = agent_bay.context.get(name=context_name, create=True)
    assert create_result.success is True
    context = create_result.context

    try:
        # List contexts
        list_result = agent_bay.context.list()
        assert list_result.success is True
        assert isinstance(list_result.contexts, list)
        assert len(list_result.contexts) > 0

        # Verify our context is in the list
        context_ids = [ctx.id for ctx in list_result.contexts]
        assert context.id in context_ids
        print(f"Found {len(list_result.contexts)} contexts")
    finally:
        agent_bay.context.delete(context)


@pytest.mark.sync
def test_context_update(agent_bay):
    """Test updating a context."""
    context_name = f"test-update-{uuid4().hex[:8]}"

    # Create context
    create_result = agent_bay.context.get(name=context_name, create=True)
    assert create_result.success is True
    context = create_result.context
    original_id = context.id

    try:
        # Update context name
        new_name = f"test-updated-{uuid4().hex[:8]}"
        context.name = new_name
        update_result = agent_bay.context.update(context)
        assert update_result.success is True
        print(f"Updated context: {context.id} to new name: {new_name}")

        # Note: Getting by context_id may not be supported, skip verification
        print("Context update completed")
    finally:
        agent_bay.context.delete(context)


@pytest.mark.sync
def test_context_with_session(agent_bay):
    """Test using context with a session."""
    from agentbay._common.params.context_sync import ContextSync
    from agentbay._common.params.session_params import CreateSessionParams

    context_name = f"test-session-ctx-{uuid4().hex[:8]}"

    # Create context
    create_result = agent_bay.context.get(name=context_name, create=True)
    assert create_result.success is True
    context = create_result.context

    try:
        # Create session with context sync
        context_sync = ContextSync(context_id=context.id, path="/tmp/test_context")
        params = CreateSessionParams(
            image_id="linux_latest", context_syncs=[context_sync]
        )

        session_result = agent_bay.create(params)
        assert session_result.success is True
        session = session_result.session
        print(f"Created session {session.session_id} with context {context.id}")

        # Cleanup session
        session.delete()
    finally:
        # Cleanup context
        agent_bay.context.delete(context)


@pytest.mark.sync
def test_context_file_operations(agent_bay):
    """Test context file upload/download URL operations."""
    context_name = f"test-file-ops-{uuid4().hex[:8]}"

    # Create context
    create_result = agent_bay.context.get(name=context_name, create=True)
    assert create_result.success is True
    context = create_result.context

    try:
        # Get upload URL
        upload_url_result = agent_bay.context.get_file_upload_url(
            context.id, "/test_file.txt"
        )
        assert upload_url_result.success is True
        assert upload_url_result.url is not None
        assert len(upload_url_result.url) > 0
        print(f"Got upload URL: {upload_url_result.url[:50]}...")

        # Get download URL (will fail if file doesn't exist, which is expected)
        try:
            download_url_result = agent_bay.context.get_file_download_url(
                context.id, "/test_file.txt"
            )
            print(f"Download URL result success: {download_url_result.success}")
        except Exception as e:
            # Expected to fail for non-existent file
            print(f"Download URL failed as expected: file not exist")
    finally:
        agent_bay.context.delete(context)
