# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated by scripts/generate_sync.py

"""Integration test for creating sessions with skills loaded.

This test calls the real backend without mocks.
"""

import os

import pytest
import pytest

from agentbay import AgentBay
from agentbay._common.params.session_params import CreateSessionParams


@pytest.fixture(scope="module")
def agent_bay():
    api_key = os.environ.get("AGENTBAY_API_KEY")
    if not api_key:
        pytest.skip("AGENTBAY_API_KEY environment variable not set")
    return AgentBay(api_key=api_key)


@pytest.mark.sync
def test_create_session_with_load_skills(agent_bay: AgentBay):
    """Creating session with load_skills=True should succeed (backend accepts the param)."""
    params = CreateSessionParams(load_skills=True)
    result = agent_bay.create(params)
    assert result.success, f"Session creation failed: {result.error_message}"
    assert result.session is not None
    try:
        pass
    finally:
        result.session.delete()


@pytest.mark.sync
def test_create_session_without_skills(agent_bay: AgentBay):
    """Creating session without load_skills should succeed."""
    params = CreateSessionParams()
    result = agent_bay.create(params)
    assert result.success, f"Session creation failed: {result.error_message}"
    assert result.session is not None
    try:
        pass
    finally:
        result.session.delete()
