# DO NOT EDIT THIS FILE MANUALLY.
# This file is auto-generated from the _async directory.

import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from agentbay import AgentBay
from agentbay.exceptions import AgentBayError

def main():
    api_key = os.environ.get("AGENTBAY_API_KEY") or "your_api_key_here"
    agent_bay = AgentBay(api_key=api_key)
    
    try:
        print("Listing contexts (Async)...")
        # Use .list() instead of .list_contexts()
        result = agent_bay.context.list()
        contexts = result.contexts
        print(f"Found {len(contexts)} contexts")
        
        for ctx in contexts[:3]:
            print(f" - {ctx.name} ({ctx.id})")

    except AgentBayError as e:
        print(f"AgentBay error: {e}")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()

